# Generated by Django 2.1.7 on 2021-06-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=32, verbose_name='账号')),
            ],
        ),
        migrations.CreateModel(
            name='broker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=32, verbose_name='券商名称')),
            ],
        ),
        migrations.CreateModel(
            name='dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dividend_date', models.DateField(verbose_name='分红日期')),
                ('position_quantity', models.IntegerField(default=0, verbose_name='持仓数量')),
                ('dividend_per_share', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='每股分红')),
                ('dividend_amount', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='分红金额（税后）')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.account', verbose_name='证券账户')),
            ],
        ),
        migrations.CreateModel(
            name='market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=32, verbose_name='市场名称')),
                ('market_abbreviation', models.CharField(max_length=32, verbose_name='市场简称')),
                ('transaction_currency', models.PositiveIntegerField(choices=[(1, '人民币'), (2, '港元'), (3, '美元')], default=1, verbose_name='交易货币')),
            ],
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_quantity', models.IntegerField(default=0, verbose_name='持仓数量')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.account', verbose_name='证券账户')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=32, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=32, verbose_name='股票名称')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.market', verbose_name='市场')),
            ],
        ),
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.PositiveIntegerField(choices=[(1, '股票'), (2, '可转债')], default=1, verbose_name='申购类型')),
                ('subscription_date', models.DateField(verbose_name='申购日期')),
                ('subscription_quantity', models.IntegerField(default=0, verbose_name='申购数量')),
                ('buying_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='买入价格')),
                ('selling_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='卖出价格')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.account', verbose_name='证券账户')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票')),
            ],
        ),
        migrations.CreateModel(
            name='trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField(verbose_name='交易日期')),
                ('trade_type', models.PositiveIntegerField(choices=[(1, '买入'), (2, '卖出')], default=1, verbose_name='交易类型')),
                ('trade_quantity', models.IntegerField(default=0, verbose_name='交易数量')),
                ('trade_price', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='交易价格')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.account', verbose_name='证券账户')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票'),
        ),
        migrations.AddField(
            model_name='account',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.broker', verbose_name='券商'),
        ),
    ]
