# Generated by Django 2.1.7 on 2021-06-29 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_remove_trade_filed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='filed_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='归档时间'),
        ),
    ]
