# Generated by Django 2.1.7 on 2021-06-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_trade_filed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='account',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='stock',
        ),
        migrations.DeleteModel(
            name='trade',
        ),
    ]
