# Generated by Django 3.2.6 on 2021-08-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_name',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='券商名称'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='industry_code',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='行业代码'),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_name',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='市场名称'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_code',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(db_index=True, max_length=32, verbose_name='股票名称'),
        ),
    ]
