# Generated by Django 3.2.6 on 2021-08-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0014_alter_dividend_dividend_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='dividend_currency',
            field=models.PositiveIntegerField(choices=[(1, '人民币'), (2, '港元'), (3, '美元')], default=1, verbose_name='分红货币'),
        ),
    ]
