# Generated by Django 3.2.6 on 2021-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_dividend_dividend_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='position_currency',
            field=models.PositiveIntegerField(choices=[(1, '人民币'), (2, '港元'), (3, '美元')], default=1, verbose_name='持仓货币'),
        ),
        migrations.AddField(
            model_name='trade',
            name='settlement_currency',
            field=models.PositiveIntegerField(choices=[(1, '人民币'), (2, '港元'), (3, '美元')], default=1, verbose_name='结算货币'),
        ),
    ]
