# Generated by Django 3.2.6 on 2021-09-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_auto_20210826_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stock',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscription_name',
            field=models.CharField(default='', max_length=32, verbose_name='申购名称'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='buying_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='买入价格'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='selling_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='卖出价格'),
        ),
    ]
