# Generated by Django 3.2.6 on 2021-10-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0018_auto_20210914_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=8, verbose_name='汇率'),
        ),
        migrations.AddField(
            model_name='market',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
