# Generated by Django 3.2.6 on 2021-11-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_auto_20211020_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='increase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='涨幅'),
        ),
        migrations.AddField(
            model_name='stock',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='价格'),
        ),
    ]
