# Generated by Django 3.2.6 on 2022-04-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_auto_20211106_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='dividend_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_period', models.CharField(max_length=64, verbose_name='报告期')),
                ('dividend_plan', models.CharField(max_length=256, verbose_name='分红方案')),
                ('announcement_date', models.DateField(verbose_name='公告日')),
                ('registration_date', models.DateField(verbose_name='股权登记日')),
                ('ex_right_date', models.DateField(verbose_name='除权除息日')),
                ('dividend_date', models.DateField(verbose_name='派息日')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票')),
            ],
        ),
    ]
