# Generated by Django 4.0.5 on 2022-07-15 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_auto_20220518_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dividend_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='分红获取时间'),
        ),
        migrations.AddField(
            model_name='stock',
            name='price_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), verbose_name='价格获取时间'),
        ),
    ]
