# Generated by Django 4.0.5 on 2022-09-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0024_stock_dividend_time_stock_price_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='increase',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price_time',
        ),
    ]
