# Generated by Django 4.0.6 on 2022-09-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_remove_stock_increase_remove_stock_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='exchange_rate',
        ),
        migrations.RemoveField(
            model_name='market',
            name='modified_time',
        ),
    ]
