# Generated by Django 4.0.5 on 2025-01-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_funds_details_funds_annualized_profit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds_details',
            name='funds_current_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='基金当期收益'),
        ),
        migrations.AddField(
            model_name='funds_details',
            name='funds_current_profit_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='基金当期收益率'),
        ),
    ]
