# Generated by Django 4.0.5 on 2025-01-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_alter_funds_details_funds_annualized_profit_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='update_date',
            field=models.DateField(blank=True, null=True, verbose_name='更新日期'),
        ),
    ]
