# Generated by Django 4.0.5 on 2025-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_funds_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='funds_base_line',
            field=models.CharField(max_length=32, null=True, verbose_name='比较基准'),
        ),
        migrations.AlterField(
            model_name='funds',
            name='funds_script',
            field=models.CharField(max_length=128, null=True, verbose_name='备注'),
        ),
    ]
