# Generated by Django 4.0.5 on 2025-02-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_funds_funds_base_line_alter_funds_funds_script'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funds',
            old_name='funds_base_line',
            new_name='funds_baseline',
        ),
    ]
