# Generated by Django 4.0.5 on 2025-02-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_rename_funds_base_line_funds_funds_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
    ]
