# Generated by Django 4.0.5 on 2025-02-27 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0034_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('quantity', models.IntegerField(default=0, verbose_name='持仓数量')),
                ('currency', models.PositiveIntegerField(choices=[(1, '人民币'), (2, '港元'), (3, '美元')], default=1, verbose_name='持仓货币')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票')),
            ],
        ),
    ]
