# Generated by Django 4.0.5 on 2025-02-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_historical_position'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='historical_position',
            constraint=models.UniqueConstraint(fields=('date', 'stock_id', 'currency'), name='unique_daily_position'),
        ),
    ]
