# Generated by Django 4.0.5 on 2025-02-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_historical_position_idx_stock_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='historical_position',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trade',
            table=None,
        ),
    ]
