# Generated by Django 5.0.12 on 2025-03-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0038_alter_historical_position_table_alter_trade_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_position',
            name='closing_price',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='收盘价格'),
        ),
    ]
