# Generated by Django 5.0.12 on 2025-03-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_historical_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='historical_market_value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('currency', models.CharField(max_length=16, verbose_name='货币')),
                ('value', models.DecimalField(decimal_places=4, max_digits=16, verbose_name='市值')),
            ],
        ),
        migrations.RenameIndex(
            model_name='historical_rate',
            new_name='stock_histo_date_9a046f_idx',
            old_name='idx_date_currency',
        ),
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['date', 'currency'], name='stock_histo_date_d712de_idx'),
        ),
    ]
