# Generated by Django 5.0.12 on 2025-03-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_historical_market_value_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historical_market_value',
            name='stock_histo_date_d712de_idx',
        ),
        migrations.RemoveIndex(
            model_name='historical_rate',
            name='stock_histo_date_9a046f_idx',
        ),
    ]
