# Generated by Django 5.0.12 on 2025-03-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_remove_historical_market_value_stock_histo_date_d712de_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['date', 'currency'], name='stock_histo_date_d712de_idx'),
        ),
        migrations.AddIndex(
            model_name='historical_rate',
            index=models.Index(fields=['date', 'currency'], name='stock_histo_date_9a046f_idx'),
        ),
    ]
