# Generated by Django 5.0.12 on 2025-03-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_historical_market_value_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historical_market_value',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='historical_market_value',
            name='modified_time',
        ),
        migrations.RemoveField(
            model_name='historical_rate',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='historical_rate',
            name='modified_time',
        ),
    ]
