# Generated by Django 5.0.12 on 2025-03-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_remove_historical_market_value_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_market_value',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='historical_rate',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
    ]
