# Generated by Django 5.0.12 on 2025-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0046_historical_market_value_modified_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_market_value',
            name='change_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='变化值'),
        ),
        migrations.AddField(
            model_name='historical_market_value',
            name='change_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='变化率(%)'),
        ),
        migrations.AddField(
            model_name='historical_market_value',
            name='prev_value',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=16, verbose_name='前一日市值'),
        ),
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['currency', '-date'], name='stock_histo_currenc_828303_idx'),
        ),
    ]
