# Generated by Django 5.0.12 on 2025-05-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0047_historical_market_value_change_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='funds_currency',
            field=models.PositiveIntegerField(choices=[(1, '人民币'), (2, '港元'), (3, '美元')], default=1, verbose_name='货币'),
        ),
    ]
