# Generated by Django 5.0.12 on 2025-06-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0048_funds_funds_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='代码')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='名称')),
                ('script', models.CharField(max_length=32, null=True, verbose_name='备注')),
            ],
        ),
    ]
