# Generated by Django 5.0.12 on 2025-06-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0050_market_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='market',
            old_name='transaction_currency',
            new_name='transaction_currency1',
        ),
    ]
