# Generated by Django 5.0.12 on 2025-06-12 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0051_rename_transaction_currency_market_transaction_currency1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='transaction_currency1',
        ),
    ]
