# Generated by Django 5.0.12 on 2025-06-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0053_position_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='position_currency',
        ),
    ]
