# Generated by Django 5.0.12 on 2025-06-13 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0057_dividend_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividend',
            name='dividend_currency',
        ),
    ]
