# Generated by Django 5.0.12 on 2025-06-13 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0059_trade_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='settlement_currency',
        ),
    ]
