# Generated by Django 5.0.12 on 2025-06-14 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0060_remove_trade_settlement_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='baseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='代码')),
                ('name', models.CharField(db_index=True, max_length=32, verbose_name='名称')),
                ('script', models.CharField(max_length=32, null=True, verbose_name='备注')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.currency', verbose_name='货币')),
            ],
        ),
    ]
