# Generated by Django 5.0.12 on 2025-06-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0061_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='baseline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.baseline', verbose_name='比较基准'),
        ),
    ]
