# Generated by Django 5.0.12 on 2025-06-14 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0062_funds_baseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funds',
            name='funds_baseline',
        ),
    ]
