# Generated by Django 5.0.12 on 2025-06-21 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0063_remove_funds_funds_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_position',
            name='currency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.currency', verbose_name='货币'),
        ),
    ]
