# Generated by Django 5.0.12 on 2025-06-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0064_historical_position_currency_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historical_position',
            name='unique_daily_position',
        ),
        migrations.RemoveIndex(
            model_name='historical_position',
            name='idx_stock_currency',
        ),
        migrations.RemoveField(
            model_name='historical_position',
            name='currency',
        ),
        migrations.AddIndex(
            model_name='historical_position',
            index=models.Index(fields=['stock_id', 'currency_type_id'], name='idx_stock_currency'),
        ),
        migrations.AddConstraint(
            model_name='historical_position',
            constraint=models.UniqueConstraint(fields=('date', 'stock_id', 'currency_type_id'), name='unique_daily_position'),
        ),
    ]
