# Generated by Django 5.0.12 on 2025-06-22 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0065_remove_historical_position_unique_daily_position_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='historical_position',
            name='unique_daily_position',
        ),
        migrations.RemoveIndex(
            model_name='historical_position',
            name='idx_stock_currency',
        ),
        migrations.AlterField(
            model_name='historical_position',
            name='currency_type',
            field=models.ForeignKey(blank=True, db_column='currency_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.currency', verbose_name='货币'),
        ),
        migrations.RenameField(
            model_name='historical_position',
            old_name='currency_type',
            new_name='currency',
        ),
        migrations.AddIndex(
            model_name='historical_position',
            index=models.Index(fields=['stock', 'currency'], name='idx_stock_currency'),
        ),
        migrations.AddConstraint(
            model_name='historical_position',
            constraint=models.UniqueConstraint(fields=('date', 'stock', 'currency'), name='unique_daily_position'),
        ),
    ]
