# Generated by Django 5.0.12 on 2025-06-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0067_historical_rate_currency_temp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historical_rate',
            name='stock_histo_date_9a046f_idx',
        ),
        migrations.RemoveField(
            model_name='historical_rate',
            name='currency',
        ),
        migrations.AddIndex(
            model_name='historical_rate',
            index=models.Index(fields=['date', 'currency_temp'], name='stock_histo_date_be18f3_idx'),
        ),
    ]
