# Generated by Django 5.0.12 on 2025-06-23 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0068_remove_historical_rate_stock_histo_date_9a046f_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historical_rate',
            name='stock_histo_date_be18f3_idx',
        ),
        migrations.RenameField(
            model_name='historical_rate',
            old_name='currency_temp',
            new_name='currency',  # 重命名字段
        ),
        migrations.AddIndex(
            model_name='historical_rate',
            index=models.Index(fields=['date', 'currency'], name='stock_histo_date_5316c7_idx'),
        ),
    ]
