# Generated by Django 5.0.12 on 2025-06-23 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0069_remove_historical_rate_stock_histo_date_be18f3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historical_market_value',
            name='currency_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency', verbose_name='临时货币外键'),
        ),
        migrations.AlterField(
            model_name='historical_rate',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency', verbose_name='货币外键'),
        ),
    ]
