# Generated by Django 5.0.12 on 2025-06-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0070_historical_market_value_currency_temp_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historical_market_value',
            name='stock_histo_date_d712de_idx',
        ),
        migrations.RemoveIndex(
            model_name='historical_market_value',
            name='stock_histo_currenc_828303_idx',
        ),
        migrations.RemoveField(
            model_name='historical_market_value',
            name='currency',
        ),
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['currency_temp', '-date'], name='stock_histo_currenc_d1336a_idx'),
        ),
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['date', 'currency_temp'], name='stock_histo_date_181582_idx'),
        ),
    ]
