# Generated by Django 5.0.12 on 2025-06-23 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0071_remove_historical_market_value_stock_histo_date_d712de_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historical_market_value',
            name='stock_histo_currenc_d1336a_idx',
        ),
        migrations.RemoveIndex(
            model_name='historical_market_value',
            name='stock_histo_date_181582_idx',
        ),
        migrations.RenameField(
            model_name='historical_market_value',
            old_name='currency_temp',
            new_name='currency',  # 重命名字段
        ),
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['currency', '-date'], name='stock_histo_currenc_31c552_idx'),
        ),
        migrations.AddIndex(
            model_name='historical_market_value',
            index=models.Index(fields=['date', 'currency'], name='stock_histo_date_8e159d_idx'),
        ),
    ]
