# Generated by Django 5.0.12 on 2025-06-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0072_remove_historical_market_value_stock_histo_currenc_d1336a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historical_market_value',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.currency', verbose_name='货币外键'),
        ),
        migrations.AlterField(
            model_name='historical_position',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.currency', verbose_name='货币'),
        ),
    ]
