# Generated by Django 5.0.12 on 2025-06-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0073_alter_historical_market_value_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='unit',
            field=models.CharField(max_length=32, null=True, verbose_name='单位'),
        ),
    ]
