# Generated by Django 5.2.5 on 2025-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0074_currency_unit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dividend_history',
            new_name='DividendHistory',
        ),
        migrations.RenameModel(
            old_name='funds_details',
            new_name='FundsDetails',
        ),
    ]
