# Generated by Django 5.2.5 on 2025-08-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0075_rename_dividend_history_dividendhistory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='historical_market_value',
            new_name='HistoricalMarketValue',
        ),
        migrations.RenameModel(
            old_name='historical_position',
            new_name='HistoricalPosition',
        ),
        migrations.RenameModel(
            old_name='historical_rate',
            new_name='HistoricalRate',
        ),
        migrations.RenameIndex(
            model_name='historicalmarketvalue',
            new_name='stock_histo_currenc_6d8a9e_idx',
            old_name='stock_histo_currenc_31c552_idx',
        ),
        migrations.RenameIndex(
            model_name='historicalmarketvalue',
            new_name='stock_histo_date_3656af_idx',
            old_name='stock_histo_date_8e159d_idx',
        ),
        migrations.RenameIndex(
            model_name='historicalrate',
            new_name='stock_histo_date_449d6c_idx',
            old_name='stock_histo_date_5316c7_idx',
        ),
    ]
