# Generated by Django 5.2.5 on 2025-10-06 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0076_rename_historical_market_value_historicalmarketvalue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='funds',
            new_name='Fund',
        ),
        migrations.RenameModel(
            old_name='FundsDetails',
            new_name='FundHistory',
        ),
    ]
