# Generated by Django 5.2.5 on 2025-10-06 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0077_rename_funds_fund_rename_fundsdetails_fundhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund',
            old_name='funds_PHR',
            new_name='fund_PHR',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_create_date',
            new_name='fund_create_date',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_name',
            new_name='fund_name',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_net_value',
            new_name='fund_net_value',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_principal',
            new_name='fund_principal',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_script',
            new_name='fund_script',
        ),
        migrations.RenameField(
            model_name='fund',
            old_name='funds_value',
            new_name='fund_value',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds',
            new_name='fund',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_PHR',
            new_name='fund_PHR',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_annualized_profit_rate',
            new_name='fund_annualized_profit_rate',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_current_profit',
            new_name='fund_current_profit',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_current_profit_rate',
            new_name='fund_current_profit_rate',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_in_out',
            new_name='fund_in_out',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_net_value',
            new_name='fund_net_value',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_principal',
            new_name='fund_principal',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_profit',
            new_name='fund_profit',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_profit_rate',
            new_name='fund_profit_rate',
        ),
        migrations.RenameField(
            model_name='fundhistory',
            old_name='funds_value',
            new_name='fund_value',
        ),
    ]
