# Generated by Django 5.2.5 on 2025-10-08 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0078_rename_funds_phr_fund_fund_phr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fund',
            new_name='Portfolio',
        ),
        migrations.RenameModel(
            old_name='FundHistory',
            new_name='PortfolioHistory',
        ),
    ]
