# Generated by Django 5.2.5 on 2025-10-08 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0079_rename_fund_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_PHR',
            new_name='portfolio_PHR',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_create_date',
            new_name='portfolio_create_date',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_name',
            new_name='portfolio_name',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_net_value',
            new_name='portfolio_net_value',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_principal',
            new_name='portfolio_principal',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_script',
            new_name='portfolio_script',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='fund_value',
            new_name='portfolio_value',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund',
            new_name='portfolio',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_PHR',
            new_name='portfolio_PHR',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_annualized_profit_rate',
            new_name='portfolio_annualized_profit_rate',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_current_profit',
            new_name='portfolio_current_profit',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_current_profit_rate',
            new_name='portfolio_current_profit_rate',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_in_out',
            new_name='portfolio_in_out',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_net_value',
            new_name='portfolio_net_value',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_principal',
            new_name='portfolio_principal',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_profit',
            new_name='portfolio_profit',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_profit_rate',
            new_name='portfolio_profit_rate',
        ),
        migrations.RenameField(
            model_name='portfoliohistory',
            old_name='fund_value',
            new_name='portfolio_value',
        ),
    ]
