# Generated by Django 5.2.5 on 2025-10-08 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0080_rename_fund_phr_portfolio_portfolio_phr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_PHR',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合份数'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_create_date',
            field=models.DateField(blank=True, null=True, verbose_name='投资组合创立日期'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(db_index=True, max_length=32, unique=True, verbose_name='投资组合名称'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_net_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='投资组合净值'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_principal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合本金'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合价值'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.portfolio', verbose_name='投资组合'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_PHR',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合份数'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_annualized_profit_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='投资组合年化收益率'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_current_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合当期收益'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_current_profit_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='投资组合当期收益率'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_net_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='投资组合净值'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_principal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合本金'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合收益'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_profit_rate',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='投资组合收益率'),
        ),
        migrations.AlterField(
            model_name='portfoliohistory',
            name='portfolio_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='投资组合价值'),
        ),
    ]
