# Generated by Django 5.2.5 on 2025-11-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0081_alter_portfolio_portfolio_phr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClosePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('closing_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=8, verbose_name='收盘价格')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='股票')),
            ],
            options={
                'indexes': [models.Index(fields=['stock', '-date'], name='stock_histo_stock_i_9489da_idx'), models.Index(fields=['date', 'stock'], name='stock_histo_date_778139_idx')],
            },
        ),
    ]
