# Generated by Django 5.2.5 on 2025-11-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0082_historicalcloseprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalClosePrice',
        ),
    ]
