# Generated by Django 5.2.5 on 2025-12-24 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0083_delete_historicalcloseprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_aggregated',
            field=models.BooleanField(default=False, verbose_name='是否为汇总投资组合'),
        ),
    ]
